name: dating_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Audio recording stack (aligned)
  record: ^6.1.1
  record_linux: ^1.2.0
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  sms_autofill: ^2.2.0
  image_picker: ^0.8.5+3
  dotted_border: ^2.0.0
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.9
  flutter_sound: ^9.2.13
  path_provider_android: ^2.2.15
  intl: ^0.18.0
  agora_rtc_engine: ^6.5.1
  permission_handler: ^11.0.0
  url_launcher: ^6.3.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  get: ^4.6.5
  flutter_native_splash: ^2.3.5
  animate_do: ^4.2.0
  font_awesome_flutter: ^10.7.0
  video_thumbnail: ^0.5.3
  http: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_storage: ^2.1.1
  google_maps_flutter: ^2.12.3
  flutter_google_places_sdk: ^0.4.2+1
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  emoji_picker_flutter: ^4.3.0
  audioplayers: ^6.5.1
  firebase_app_check: ^0.4.0+1
  reorderable_grid_view: ^2.2.8
  flutter_reorderable_grid_view: ^4.0.0
  flutter_secure_storage: ^9.2.2
  video_player: ^2.9.1
  add_2_calendar: ^3.0.1
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_launcher_icons: ^0.13.1


dependency_overrides:
  # Keep only the Places overrides you actually need
  flutter_google_places_sdk_platform_interface: ^0.3.0
  flutter_google_places_sdk_http: ^0.2.1
  flutter_google_places_sdk_linux: ^0.2.1
  flutter_google_places_sdk_windows: ^0.2.1

  # IMPORTANT: remove these two overrides to avoid conflicts
  # record_platform_interface: 1.3.0
  # record_linux: any
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/AppIcon.png
  remove_alpha_ios: true


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  test: ^1.24.0
  mockito: ^5.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/image@2x (1).jpg
    - assets/Pairup (1) 1.jpg
    - assets/Pairup 1@2x.jpg
    - assets/Pairup (1) 3.jpg
    - assets/Pairup 1.svg
    - assets/Pairup (1) aa.jpg
    - assets/profileimage.png
    - assets/welcomelogo.png
    - assets/applogo.png
    - assets/applogo_transparent.png
    - assets/profilevideoimage.png
    - assets/dpjohn.png
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/image4.png
    - assets/image5.png
    - assets/image6.png
    - assets/event1.png
    - assets/event2.png
    - assets/event3.png
    - assets/dp1.png
    - assets/dp2.png
    - assets/dp3.png
    - assets/mainlogo2.png
    - assets/facebooklogo.png
    - assets/instalogo.png
    - assets/splash_logo.png
    - assets/video.png
    - assets/image (7).png
    - assets/the_pairup_logo_black.png
    - assets/pairupbottom.png
    - assets/categories.json
    - assets/AppIcon.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
